# This file is auto-generated from the database schema defined in
# the migrations. Do not edit this file directly.

ActiveRecord::Schema[7.1].define(version: 20260102000006) do
  create_table "users", force: :cascade do |t|
    t.string "email", null: false
    t.string "password_digest", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["email"], name: "index_users_on_email", unique: true
  end

  create_table "stores", force: :cascade do |t|
    t.string "name", null: false
    t.string "subdomain", null: false
    t.text "description"
    t.bigint "user_id", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["subdomain"], name: "index_stores_on_subdomain", unique: true
    t.index ["user_id"], name: "index_stores_on_user_id"
  end

  create_table "products", force: :cascade do |t|
    t.string "name", null: false
    t.text "description"
    t.decimal "price", precision: 10, scale: 2, null: false
    t.bigint "store_id", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["store_id"], name: "index_products_on_store_id"
  end

  create_table "variants", force: :cascade do |t|
    t.string "name", null: false
    t.decimal "price", precision: 10, scale: 2
    t.bigint "product_id", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["product_id"], name: "index_variants_on_product_id"
  end

  create_table "customers", force: :cascade do |t|
    t.string "email", null: false
    t.string "first_name"
    t.string "last_name"
    t.string "password_digest"
    t.string "remember_token"
    t.bigint "store_id", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["email", "store_id"], name: "index_customers_on_email_and_store_id", unique: true
    t.index ["store_id"], name: "index_customers_on_store_id"
  end

  create_table "orders", force: :cascade do |t|
    t.decimal "total", precision: 10, scale: 2, null: false
    t.string "status", null: false
    t.bigint "customer_id", null: false
    t.bigint "store_id", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["customer_id"], name: "index_orders_on_customer_id"
    t.index ["store_id"], name: "index_orders_on_store_id"
  end

  create_table "order_items", force: :cascade do |t|
    t.integer "quantity", null: false
    t.decimal "price", precision: 10, scale: 2, null: false
    t.bigint "order_id", null: false
    t.bigint "variant_id", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["order_id"], name: "index_order_items_on_order_id"
    t.index ["variant_id"], name: "index_order_items_on_variant_id"
  end

  create_table "payments", force: :cascade do |t|
    t.decimal "amount", precision: 10, scale: 2, null: false
    t.string "status", null: false
    t.string "provider"
    t.string "stripe_payment_id"
    t.bigint "order_id", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["order_id"], name: "index_payments_on_order_id"
  end

  create_table "themes", force: :cascade do |t|
    t.string "name", null: false
    t.bigint "store_id", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["store_id"], name: "index_themes_on_store_id"
  end

  create_table "theme_templates", force: :cascade do |t|
    t.string "name", null: false
    t.text "content"
    t.bigint "theme_id", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["theme_id"], name: "index_theme_templates_on_theme_id"
  end

  create_table "domains", force: :cascade do |t|
    t.string "name", null: false
    t.boolean "verified", default: false
    t.text "verification_token"
    t.datetime "verified_at"
    t.bigint "store_id", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["name"], name: "index_domains_on_name", unique: true
    t.index ["store_id"], name: "index_domains_on_store_id"
  end

  create_table "plans", force: :cascade do |t|
    t.string "name", null: false
    t.decimal "price", precision: 10, scale: 2, null: false
    t.string "interval", null: false
    t.integer "product_limit", default: 10
    t.json "features"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "subscriptions", force: :cascade do |t|
    t.string "status", null: false
    t.string "stripe_subscription_id"
    t.bigint "store_id", null: false
    t.bigint "plan_id", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["plan_id"], name: "index_subscriptions_on_plan_id"
    t.index ["store_id"], name: "index_subscriptions_on_store_id"
  end

  create_table "carts", force: :cascade do |t|
    t.string "token", null: false
    t.bigint "store_id", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["store_id"], name: "index_carts_on_store_id"
    t.index ["token"], name: "index_carts_on_token", unique: true
  end

  create_table "cart_items", force: :cascade do |t|
    t.integer "quantity", null: false
    t.bigint "cart_id", null: false
    t.bigint "variant_id", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["cart_id"], name: "index_cart_items_on_cart_id"
    t.index ["variant_id"], name: "index_cart_items_on_variant_id"
  end

  create_table "discounts", force: :cascade do |t|
    t.string "code", null: false
    t.decimal "amount", precision: 10, scale: 2
    t.integer "percentage"
    t.integer "usage_limit"
    t.integer "used_count", default: 0
    t.datetime "expires_at"
    t.bigint "store_id", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["code", "store_id"], name: "index_discounts_on_code_and_store_id", unique: true
    t.index ["store_id"], name: "index_discounts_on_store_id"
  end

  create_table "shipping_zones", force: :cascade do |t|
    t.string "name", null: false
    t.string "country", null: false
    t.decimal "rate", precision: 10, scale: 2, null: false
    t.bigint "store_id", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["store_id"], name: "index_shipping_zones_on_store_id"
  end

  create_table "shipping_rates", force: :cascade do |t|
    t.string "name", null: false
    t.decimal "rate", precision: 10, scale: 2, null: false
    t.bigint "shipping_zone_id", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["shipping_zone_id"], name: "index_shipping_rates_on_shipping_zone_id"
  end

  create_table "store_memberships", force: :cascade do |t|
    t.string "role", null: false
    t.bigint "store_id", null: false
    t.bigint "user_id", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["store_id"], name: "index_store_memberships_on_store_id"
    t.index ["user_id"], name: "index_store_memberships_on_user_id"
  end

  add_foreign_key "stores", "users"
  add_foreign_key "products", "stores"
  add_foreign_key "variants", "products"
  add_foreign_key "customers", "stores"
  add_foreign_key "orders", "customers"
  add_foreign_key "orders", "stores"
  add_foreign_key "order_items", "orders"
  add_foreign_key "order_items", "variants"
  add_foreign_key "payments", "orders"
  add_foreign_key "themes", "stores"
  add_foreign_key "theme_templates", "themes"
  add_foreign_key "domains", "stores"
  add_foreign_key "subscriptions", "plans"
  add_foreign_key "subscriptions", "stores"
  add_foreign_key "carts", "stores"
  add_foreign_key "cart_items", "carts"
  add_foreign_key "cart_items", "variants"
  add_foreign_key "discounts", "stores"
  add_foreign_key "shipping_zones", "stores"
  add_foreign_key "shipping_rates", "shipping_zones"
  add_foreign_key "store_memberships", "stores"
  add_foreign_key "store_memberships", "users"
end
